# Generated by Django 6.0 on 2025-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='naz')),
                ('anons', models.CharField(max_length=100, verbose_name='anons')),
                ('full', models.TextField(verbose_name='full')),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
